AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to launch an Instance for self service Security Review
Parameters:
  SelfServiceSecVPCID:
    Type: String
  SubnetAID:
    Type: String
  SelfServiceSecS3Bucket:
    Type: String
  InstanceRoleName:
    Type: String
  LatestAmiId:
    Type:  'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
Resources:
  rInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "SelfServiceSec Security Instance SG"
      VpcId: !Ref SelfServiceSecVPCID
      Tags:
      - Key: Name
        Value: "SelfServiceSecSecurityGroup"
  rEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: m5a.large
      Tags:
      - Key: Name
        Value: "SelfServiceSecSecurityInstance"
      SecurityGroupIds:
       - !GetAtt "rInstanceSG.GroupId"
      ImageId: !Ref 'LatestAmiId'
      SubnetId: !Ref SubnetAID
      IamInstanceProfile: !Ref InstanceRoleName
      # This will update the Instance, pull Prowler, run and then write to the output to the S3 Bucket
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum -y update
          yum groupinstall "Development Tools" -y
          sudo yum -y install gcc openssl-devel bzip2-devel libffi-devel
          wget https://www.python.org/ftp/python/3.9.16/Python-3.9.16.tgz
          tar zxf Python-3.9.16.tgz
          cd Python-3.9.16/
          ./configure --enable-optimizations
          sudo make altinstall
          export PATH=$PATH:/usr/local/bin
          pip3.9 install prowler
          cd 
          aws configure set default.region ${AWS::Region}
          prowler aws | tee prowler-output.txt
          aws s3 cp prowler-output.txt s3://${SelfServiceSecS3Bucket}
          aws s3 cp output s3://${SelfServiceSecS3Bucket} --recursive
          /sbin/init 0
