AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template IAM Role for SelfServiceSec Security
Parameters:
  SelfServiceSecS3Bucket:
    Type: String
Resources:
  #This is the only Role created
  rSelfServiceSecSecurityRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ssm.amazonaws.com
            - ec2.amazonaws.com
            - lambda.amazonaws.com
          Action: sts:AssumeRole
      #Managed Policies attached for ScoutSuite
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      - arn:aws:iam::aws:policy/SecurityAudit
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: "/"
      RoleName: SelfServiceSecSecurityRole
  # The Instance Profile is required for EC2 Instance Roles
  rSelfServiceSecSecurityInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: SelfServiceSecSecurityRole
      Path: "/"
      Roles:
        - !Ref rSelfServiceSecSecurityRole
  #This policy is required to write the output to the Bucket
  rSelfServiceSecS3Policy:
   Type: AWS::IAM::ManagedPolicy
   Properties:
    Roles:
    - !Ref rSelfServiceSecSecurityRole
    Description: Policy for SelfServiceSec Reports
    Path: "/"
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
      - Action:
        - s3:PutObject
        Effect: Allow
        Resource: !Join
            - ''
            - - 'arn:'
              - !Ref 'AWS::Partition'
              - ':s3:'
              - '::'
              - !Ref SelfServiceSecS3Bucket
              - '/*'
  #Additional Rights as required by Prowler
  rSelfServiceSecProwlerPolicy:
   Type: AWS::IAM::ManagedPolicy
   Properties:
    Roles:
    - !Ref rSelfServiceSecSecurityRole
    Description: Policy for Prowler
    Path: "/"
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
      - Action:
        - appstream:Describe*
        - codeartifact:List*
        - codebuild:BatchGet*
        - ds:Describe*
        - ds:Get*
        - ds:List*
        - ec2:GetEbsEncryptionByDefault
        - ecr:Describe*
        - elasticfilesystem:DescribeBackupPolicy
        - glue:GetConnections
        - glue:GetSecurityConfiguration*
        - glue:SearchTables
        - lambda:GetFunction*
        - macie2:GetMacieSession
        - s3:GetAccountPublicAccessBlock
        - s3:GetPublicAccessBlock
        - shield:DescribeProtection
        - shield:GetSubscriptionState
        - ssm:GetDocument
        - support:Describe*
        - tag:GetTagKeys
        - backup:ListBackupJobs
        - ssm:SendCommand
        Effect: Allow
        Resource: "*"
Outputs:
  InstanceRoleName:
    Description: 'Instance Role'
    Value: !Ref rSelfServiceSecSecurityRole
  InstanceRoleARN:
    Description: 'Instance Role ARN'
    Value: !GetAtt rSelfServiceSecSecurityRole.Arn
